/**
 * Display helpers for user-facing identifiers.
 * Keep internal IDs intact, but prevent long hashes from breaking layout.
 */

function abbreviate(value: string, head: number, tail: number): string {
  if (value.length <= head + tail + 3) return value;
  return `${value.slice(0, head)}...${value.slice(-tail)}`;
}

export function formatLogicalId(value: string | null | undefined): string {
  const id = String(value || '').trim();
  if (!id) return '';

  // Preserve human-readable IDs generated by backend.
  if (/^#FG-[A-Z]+-\d+$/i.test(id)) {
    return id;
  }

  // Common on-chain 32-byte hex identifiers.
  if (/^[0-9a-f]{64}$/i.test(id)) {
    return abbreviate(id, 10, 8);
  }

  // Generic long identifiers.
  if (id.length > 32) {
    return abbreviate(id, 12, 8);
  }

  return id;
}
